# Generated by Django 3.0.5 on 2020-04-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='short_info',
            field=models.TextField(default='Краткая информация о курсе', max_length=500),
        ),
        migrations.AlterField(
            model_name='course',
            name='info',
            field=models.TextField(),
        ),
    ]
