# Generated by Django 3.0.5 on 2020-04-16 16:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0004_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marathon.Lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marathon.Student')),
            ],
        ),
    ]
