# Generated by Django 3.0.5 on 2020-04-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0005_lessonmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='you_tube_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='info',
            field=models.TextField(max_length=1000),
        ),
    ]
