# Generated by Django 3.0.5 on 2020-04-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0006_auto_20200417_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='you_tube_url',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
