# Generated by Django 3.0.5 on 2020-04-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0007_auto_20200417_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='info',
            field=models.TextField(),
        ),
    ]
