# Generated by Django 3.0.5 on 2020-04-19 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0011_coursecomment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecomment',
            name='parent',
        ),
    ]
