# Generated by Django 3.0.5 on 2020-04-19 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0013_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marathon.Person'),
        ),
    ]
