# Generated by Django 3.0.5 on 2020-04-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0016_student_secret_quest'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='secret_course',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
