# Generated by Django 3.0.5 on 2020-04-21 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_auto_20200421_1254'),
        ('marathon', '0017_auto_20200421_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='age_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testing.AgeCategory', verbose_name='Возрастная категория'),
        ),
    ]
