# Generated by Django 3.0.5 on 2020-04-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0018_student_age_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['pk']},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='active',
        ),
        migrations.AddField(
            model_name='lesson',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
