# Generated by Django 3.0.5 on 2020-04-21 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0017_auto_20200421_0703'),
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.Test', verbose_name='test'),
        ),
        migrations.AlterField(
            model_name='test',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testing.AgeCategory', verbose_name='category'),
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marathon.Student', verbose_name='student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.Test', verbose_name='test')),
            ],
            options={
                'verbose_name': 'TestResults',
                'verbose_name_plural': 'Test Resultss',
            },
        ),
        migrations.CreateModel(
            name='ResultAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_ans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.Answer', verbose_name='answer')),
                ('testresult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.TestResult', verbose_name='test_result')),
            ],
            options={
                'verbose_name': 'ResultAnswer',
                'verbose_name_plural': 'ResultAnswers',
            },
        ),
    ]
