# Generated by Django 3.0.5 on 2020-04-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_auto_20200421_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='multiple',
            field=models.BooleanField(default=False),
        ),
    ]
